### PR TITLE
Update dependencies to 1.0

### PR DESCRIPTION
**Pull request by ametisf**
Minimal changes to move onto the stable versions of `proc-macro2`, `syn` and `quote`.

### CODE REVIEW

**Comment by gsingh93** [comment]
Thanks! I don't have time to test this thoroughly, could you verify that you've ran each example and and the expected output makes sense (we don't have proper tests at the moment)?

**Comment by ametisf** [comment]
I see you have an open issue about converting examples to test. I've never used gag-rs, but if you wouldn't mind a different test framework I can convert the examples to [trybuild](https://github.com/dtolnay/trybuild) tests. Also do you mind if I just append it to this PR?

**Comment by ametisf** [comment]
Sorry, I confused myself a bit. Trybuild is for UI testing, not for testing proc_macro output. I'm not sure how to test that with cargo, I'll look into it more but I'll definitely do that in a separate PR if I find something.

I compared the outputs with the previous commit and they were identical. Appending the testing script I used.

```bash
#!/bin/bash

test_example() {
    # original
    git checkout 43d43aad0c4f21e5f02b78bed2770d67766b150c
    cargo clean
    cargo expand --example $1 > /tmp/trace-old-$1.output

    # patch
    git checkout e99ef6ddac86745c99a8930bdb56d6d71550b765
    cargo clean
    cargo expand --example $1 > /tmp/trace-new-$1.output

    diff -s /tmp/trace-new-$1.output /tmp/trace-old-$1.output
}

for name in $(ls examples); do
    test_example ${name%.rs}
done
```

**Comment by gsingh93** [comment]
Thanks!

**Pull request merged**
